#ifndef DIMS_H
#define DIMS_H

#define BOARD_BORDER_L 1
#define BOARD_BORDER_R 1
#define BOARD_BORDER_U 1
#define BOARD_BORDER_D 1

#define BOARD_WIDTH 60
#define BOARD_HEIGHT 40

#define WINDOW_WIDTH BOARD_WIDTH + BOARD_BORDER_L + BOARD_BORDER_R
#define WINDOW_HEIGHT BOARD_HEIGHT + BOARD_BORDER_U + BOARD_BORDER_D

#endif // DIMS_H

