#ifndef DIMS_H
#define DIMS_H

#define WINDOW_WIDTH 80
#define WINDOW_HEIGHT 30

#define BOARD_BORDER_L 1
#define BOARD_BORDER_R 1
#define BOARD_BORDER_U 1
#define BOARD_BORDER_D 1

#define BOARD_WIDTH (WINDOW_WIDTH - BOARD_BORDER_L - BOARD_BORDER_R)
#define BOARD_HEIGHT (WINDOW_HEIGHT - BOARD_BORDER_U - BOARD_BORDER_D)

#endif // DIMS_H

